### ISSUE TITLE
Define UI color constants

### ISSUE THREAD

**Issue by chuck-adaptive** [chuck-adaptive/ui-kit-2022#20]
Defined based on the design system here: https://www.figma.com/file/vVwPje7l17NXssVR86wfYn/Reactive-Analytics---Design-System?node-id=1%3A3

The colors should be part of the MUI Theme

**Comment by iandilling-adaptive** [comment]
TODO: I've started integrating them into two MUI compatible themes: a light and a dark theme. I need to figure out how to map the design system colors to MUI's theme palette properties for each theme type (light and dark), particularly the Core-Primary and Core-Secondary colors. MUI has three properties for the "primary" and "secondary" palette colors: "light", "dark", and "main". The "light" and "dark" here are not the same as the theme mode (light mode or dark mode), they are a light and dark variant of the "main" color. So there will have to be a set of "light, "dark", and "main" for each theme color type (primary, secondary, error, etc.) for each theme (light/dark). Some colors might be in both themes, under a different "light", "dark", or "main" property depending on if the theme is light or dark. The challenge is to figure out which color can be assigned to where in both the light and dark themes.
