### ISSUE TITLE
Define UI typeface constants

### ISSUE THREAD

**Issue by chuck-adaptive** [chuck-adaptive/ui-kit-2022#21]
Defined based on the design system here: https://www.figma.com/file/vVwPje7l17NXssVR86wfYn/Reactive-Analytics---Design-System?node-id=0%3A1

* Include installation instructions for a font or bundling of the font
* accessible via the theme obejct

**Comment by iandilling-adaptive** [comment]
See the [MUI theme structure](https://mui.com/material-ui/customization/default-theme/). Design system tokens for typography will go under the `typography` field.
